import './style.css';

const categories = ['Fixed-Wing UAVs','Multirotor UAVs','Single-Rotor UAVs (Helicopter)','VTOL UAVs','Hybrid UAVs','Lighter-than-Air UAVs','Flapping-Wing / Ornithopter UAVs','Unconventional / Experimental UAVs'];
const objectiveTypes = ['Unit test','Integration test','Requirement verification','Exploratory test','Regression test','Stress test','Acceptance test','User or stakeholder feedback test'];
const results = ['Pending','Pass','Pass with observations','Fail','Aborted'];
const key = 'dft-reporter-ios-draft-v1';

const blankFlight = (n) => ({ number:n, dateTime:new Date().toISOString().slice(0,16), batteryId:'', missionId:'', duration:'', modes:'', mission:'', telemetry:'', anomalies:'', expected:'', action:'', findings:'', notes:'', result:'Pending', logName:'', captureName:'', attachments:[] });
let report = { testId:'', project:'', objectiveType:'', objective:'', location:'', operator:'', observer:'', category:'', model:'', serial:'', controller:'', groundControl:'', firmware:'', weather:'', flights:[blankFlight(1)] };
let active = 0;

const app = document.querySelector('#app');
const esc = (v='') => String(v).replace(/[&<>\"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\\':'&#92;'}[c]));
const save = () => localStorage.setItem(key, JSON.stringify(report));
const load = () => { try { const v = JSON.parse(localStorage.getItem(key)); if (v?.flights?.length) report = v; } catch {} };
const field = (label,id,value,type='input',placeholder='') => `<label>${label}${type==='textarea'?`<textarea id="${id}" placeholder="${placeholder}">${esc(value)}</textarea>`:`<input id="${id}" value="${esc(value)}" placeholder="${placeholder}" />`}</label>`;
const select = (label,id,options,value) => `<label>${label}<select id="${id}"><option value="">Select...</option>${options.map(x=>`<option ${x===value?'selected':''}>${esc(x)}</option>`).join('')}</select></label>`;

function render(){
  const f=report.flights[active];
  app.innerHTML=`<header><div><h1>Drone Flight Test Reporter</h1><p>iOS version • Offline multi-flight reporting</p></div><div class="actions"><button id="new">New Report</button><button id="save">Save</button><button id="share">Share</button></div></header>
  <main>
    <section class="card"><h2>Test Report</h2>${field('Test ID','testId',report.testId,'input','FT-2026-0015')}${field('Project / Customer','project',report.project,'input','Autonomous Mission Test')}${select('Test Objective Type','objectiveType',objectiveTypes,report.objectiveType)}${field('Test Objective','objective',report.objective,'textarea','Describe what this test campaign is intended to verify.')}${field('Location','location',report.location,'input','Test site / airfield')}<div class="grid">${field('Operator','operator',report.operator)}${field('Observer','observer',report.observer)}</div><div class="grid">${select('UAV / Aircraft Category','category',categories,report.category)}${field('Specific Aircraft / Model','model',report.model,'input','e.g. DJI Matrice 30T')}</div>${field('Serial Number','serial',report.serial)}${field('Flight Controller / Autopilot','controller',report.controller,'input','PX4 / ArduPilot')}${field('Ground Control Software','groundControl',report.groundControl,'input','QGroundControl / Mission Planner')}${field('Firmware','firmware',report.firmware)}${field('General Weather / Environment','weather',report.weather,'textarea','Wind, temperature, visibility, conditions...')}</section>
    <section class="card"><div class="row"><h2>Flights (${report.flights.length})</h2><div class="actions"><button id="addFlight">+ Add Flight</button>${report.flights.length>1?'<button id="removeFlight">Remove</button>':''}</div></div><div class="flight-tabs">${report.flights.map((x,i)=>`<button class="tab ${i===active?'active':''}" data-flight="${i}">Flight ${String(i+1).padStart(2,'0')}<small>${esc(x.result)}</small></button>`).join('')}</div>
    <div class="row"><h2>Flight ${String(f.number).padStart(2,'0')}</h2>${select('Result','result',results,f.result)}</div><div class="grid">${field('Flight Date & Time','dateTime',f.dateTime)}${field('Battery ID','batteryId',f.batteryId,'input','BATT-132')}</div><div class="grid-3">${field('Mission ID','missionId',f.missionId)}${field('Flight Duration','duration',f.duration,'input','12:34')}${field('Flight Modes','modes',f.modes,'input','Mission, RTL, Loiter')}</div>${field('Mission Performed','mission',f.mission,'textarea')}${field('Telemetry Summary','telemetry',f.telemetry,'textarea')}
    <div class="grid">${field('Anomalies / Bugs','anomalies',f.anomalies,'textarea')}${field('Expected Behaviour','expected',f.expected,'textarea')}</div><div class="grid">${field('Immediate Action','action',f.action,'textarea')}${field('Result / Findings','findings',f.findings,'textarea')}</div>${field('Operator Notes / Timeline','notes',f.notes,'textarea','10:32 — Pre-flight checks completed\n10:35 — Takeoff')}
    <div class="grid"><label>Flight Log<input id="log" type="file" /></label><label>Wireshark Capture<input id="capture" type="file" /></label></div><label>Evidence / Attachments<input id="attachments" type="file" multiple /></label></section>
    <section class="card"><div class="row"><h2>Report Preview</h2><button id="print">Export / Print PDF</button></div><div id="preview" class="preview"></div></section>
  </main>`;
  bind(); updatePreview();
}
function sync(){ const ids=['testId','project','objectiveType','objective','location','operator','observer','category','model','serial','controller','groundControl','firmware','weather']; ids.forEach(id=>{const el=document.getElementById(id);if(el)report[{testId:'testId',project:'project',objectiveType:'objectiveType',objective:'objective',location:'location',operator:'operator',observer:'observer',category:'category',model:'model',serial:'serial',controller:'controller',groundControl:'groundControl',firmware:'firmware',weather:'weather'}[id]]=el.value;}); const f=report.flights[active]; ['dateTime','batteryId','missionId','duration','modes','mission','telemetry','anomalies','expected','action','findings','notes','result'].forEach(id=>{const el=document.getElementById(id);if(el)f[id]=el.value;}); save(); }
function bind(){ document.querySelectorAll('input,textarea,select').forEach(el=>el.addEventListener('input',sync)); document.querySelectorAll('[data-flight]').forEach(b=>b.onclick=()=>{sync();active=+b.dataset.flight;render();}); document.querySelector('#addFlight').onclick=()=>{sync();report.flights.push(blankFlight(report.flights.length+1));active=report.flights.length-1;render();}; document.querySelector('#removeFlight')?.addEventListener('click',()=>{sync();report.flights.splice(active,1);report.flights.forEach((x,i)=>x.number=i+1);active=Math.min(active,report.flights.length-1);render();}); document.querySelector('#new').onclick=()=>{if(confirm('Start a new report?')){report={testId:'',project:'',objectiveType:'',objective:'',location:'',operator:'',observer:'',category:'',model:'',serial:'',controller:'',groundControl:'',firmware:'',weather:'',flights:[blankFlight(1)]};active=0;save();render();}}; document.querySelector('#save').onclick=()=>{sync();alert('Report saved on this iPhone.');}; document.querySelector('#share').onclick=share; document.querySelector('#print').onclick=()=>window.print(); document.querySelector('#log').onchange=e=>report.flights[active].logName=e.target.files[0]?.name||''; document.querySelector('#capture').onchange=e=>report.flights[active].captureName=e.target.files[0]?.name||''; document.querySelector('#attachments').onchange=e=>report.flights[active].attachments=[...e.target.files].map(x=>x.name); }
function result(){const r=report.flights.map(f=>f.result);if(r.includes('Fail'))return 'FAIL';if(r.includes('Aborted'))return 'ABORTED';if(r.includes('Pass with observations'))return 'PASS WITH OBSERVATIONS';if(r.every(x=>x==='Pass'))return 'PASS';return 'PENDING';}
function updatePreview(){const p=document.querySelector('#preview');if(!p)return;p.innerHTML=`<h1>Drone Flight Test Report — ${esc(report.testId||'Untitled')}</h1><p><b>Project:</b> ${esc(report.project||'N/A')}<br><b>Test Objective Type:</b> ${esc(report.objectiveType||'N/A')}<br><b>Overall Result:</b> ${result()}</p><h3>Test Objective</h3><p>${esc(report.objective||'N/A').replace(/\n/g,'<br>')}</p><h3>Aircraft</h3><p><b>UAV Category:</b> ${esc(report.category||'N/A')}<br><b>Aircraft / Model:</b> ${esc(report.model||'N/A')}<br><b>Serial:</b> ${esc(report.serial||'N/A')}</p><hr>${report.flights.map(f=>`<article><h2>Flight ${String(f.number).padStart(2,'0')} — ${esc(f.result)}</h2><p><b>Mission:</b> ${esc(f.missionId||'N/A')}<br><b>Battery:</b> ${esc(f.batteryId||'N/A')}<br><b>Duration:</b> ${esc(f.duration||'N/A')}</p><h3>Mission</h3><p>${esc(f.mission||'N/A').replace(/\n/g,'<br>')}</p><h3>Telemetry</h3><p>${esc(f.telemetry||'N/A').replace(/\n/g,'<br>')}</p><h3>Anomaly / Bug</h3><p>${esc(f.anomalies||'None reported').replace(/\n/g,'<br>')}</p><h3>Expected Behaviour</h3><p>${esc(f.expected||'N/A').replace(/\n/g,'<br>')}</p><h3>Immediate Action</h3><p>${esc(f.action||'None').replace(/\n/g,'<br>')}</p><h3>Findings</h3><p>${esc(f.findings||'N/A').replace(/\n/g,'<br>')}</p><h3>Operator Timeline</h3><p>${esc(f.notes||'N/A').replace(/\n/g,'<br>')}</p><h3>Evidence</h3><p>Flight log: ${esc(f.logName||'None')}<br>Wireshark: ${esc(f.captureName||'None')}<br>Attachments: ${esc((f.attachments||[]).join(', ')||'None')}</p></article>`).join('')}`;}
async function share(){sync();const text=document.querySelector('#preview').innerText; if(navigator.share){try{await navigator.share({title:'Drone Flight Test Report',text});}catch{}}else alert('Use the browser/iOS share menu to export the report.');}
load();render();
